version: "3"

services:
  backend:
    container_name: flask_backend
    build: ./backend
    depends_on:
      - database
    volumes:
      - "./backend:/backend"
    ports:
      - "5000:5000"
    env_file: config/.flask.env

  database:
    container_name: pg_database
    image: postgres
    restart: always
    volumes:
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file: config/.postgres.env

volumes:
  pg_data:
