version: "3"

services:
  backend:
    container_name: flask_backend
    build: ./backend
    depends_on:
      - database
    volumes:
      - "./backend:/backend"
    ports:
      - "5001:5001"
    env_file: config/.flask.env

  database:
    container_name: pg_database
    image: postgres
    restart: always
    volumes:
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file: config/.postgres.env

  frontend:
    container_name: react_frontend
    build: ./frontend
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    ports:
      - "3000:3000"
    env_file: config/.react.env

volumes:
  pg_data:
