name: Docker
on:
  push:
    branches:
      - "main"
      - "renovate/*"

jobs:
  build:
    name: "Build (${{ matrix.context }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        context: [frontend, backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          file: ${{ matrix.context }}/Dockerfile
          tags: |
            ghcr.io/csesoc/jobs-board-${{ matrix.context }}:${{ github.sha }}
            ghcr.io/csesoc/jobs-board-${{ matrix.context }}:latest
          labels: ${{ steps.meta.outputs.labels }}
